development:
  adapter: mysql
  database: UpdateMultiplePageElementsWithAjax_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: UpdateMultiplePageElementsWithAjax_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: UpdateMultiplePageElementsWithAjax_production
  username: root
  password: 
  socket: /tmp/mysql.sock
