development:
  adapter: mysql
  database: KeepingTrackOfWhoDidWhat_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: KeepingTrackOfWhoDidWhat_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: KeepingTrackOfWhoDidWhat_production
  username: root
  password: 
  socket: /tmp/mysql.sock
