development:
  adapter: mysql
  database: AutomaticallySaveADraft_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: AutomaticallySaveADraft_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: AutomaticallySaveADraft_production
  username: root
  password: 
  socket: /tmp/mysql.sock
