development:
  adapter: mysql
  database: MeaningfulURLs_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: MeaningfulURLs_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: MeaningfulURLs_production
  username: root
  password: 
  socket: /tmp/mysql.sock
