development:
  adapter: mysql
  database: KeepAnEyeOnYourSessionExpiry_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: KeepAnEyeOnYourSessionExpiry_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: KeepAnEyeOnYourSessionExpiry_production
  username: root
  password: 
  socket: /tmp/mysql.sock
