development:
  adapter: mysql
  database: SharingModelsBetweenApplications_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: SharingModelsBetweenApplications_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: SharingModelsBetweenApplications_production
  username: root
  password: 
  socket: /tmp/mysql.sock
