development:
  adapter: mysql
  database: HandlingBouncedMail_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: HandlingBouncedMail_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: HandlingBouncedMail_production
  username: root
  password: 
  socket: /tmp/mysql.sock
