development:
  adapter: mysql
  database: DealingWithTimeZones_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: DealingWithTimeZones_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: DealingWithTimeZones_production
  username: root
  password: 
  socket: /tmp/mysql.sock
