development:
  adapter: mysql
  database: DebuggingAjax_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: DebuggingAjax_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: DebuggingAjax_production
  username: root
  password: 
  socket: /tmp/mysql.sock
