development:
  adapter: mysql
  database: AjaxFileUploads_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: AjaxFileUploads_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: AjaxFileUploads_production
  username: root
  password: 
  socket: /tmp/mysql.sock
