development:
  adapter: mysql
  database: MakePrettyGraphs_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: MakePrettyGraphs_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: MakePrettyGraphs_production
  username: root
  password: 
  socket: /tmp/mysql.sock
