development:
  adapter: mysql
  database: CheapAndEasyThemeSupport_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: CheapAndEasyThemeSupport_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: CheapAndEasyThemeSupport_production
  username: root
  password: 
  socket: /tmp/mysql.sock
