development:
  adapter: mysql
  database: EasyHTMLWhitelists_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: EasyHTMLWhitelists_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: EasyHTMLWhitelists_production
  username: root
  password: 
  socket: /tmp/mysql.sock
