development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myrailsdatabase_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

products:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: products
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

