development:
  adapter: mysql
  database: StaticAjax_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: StaticAjax_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: StaticAjax_production
  username: root
  password: 
  socket: /tmp/mysql.sock
